### ISSUE TITLE
When declaring "height: 100%" on the body, total body height is 100% + 16px

### ISSUE THREAD

**Issue by PanzerKunst** [14islands/js-breakpoints#13]
Hi,

I just noticed that there was the scrollbar displayed in Chrome, when using js-breakpoints together with a CSS declaration of `height: 100%` on the `body` element.

This is because on `body:after`, there is a 16px high element, which gets added to a body already filling the whole viewport.

The reason for declaring `height: 100%` on the body is to have a footer which is at the bottom of the page even when the page content is less than the viewport height.

Any suggestion on how to get rid of the extra 16px in such a situation?

**Comment by ffdead** [comment]
Hi there,

I think this might have been fixed by this pull request: https://github.com/14islands/js-breakpoints/pull/12

Could you take a pull and try it out please?

**Comment by PanzerKunst** [comment]
That's right, I was using an old version. Problem solved :)
